name: gnn
channels:
  - pytorch
  - nvidia
  - dglteam/label/th23_cu121
dependencies:
  - python=3.11
  - setuptools=68
  - tqdm
  - pyyaml
  - pydantic
  - numpy
  - pandas
  - scikit-learn
  - pytorch=2.3
  - pytorch-cuda=12.1
  - torchdata=0.7
  - dgl
