name: gnn
channels:
  - pytorch
  - nvidia
  - dglteam/label/th23_cu118
dependencies:
  - tqdm
  - pyyaml
  - numpy
  - pandas
  - scikit-learn
  - cudatoolkit=11.8
  - pytorch
  - pytorch-cuda=11.8
  - dgl
